// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace WuwaGameplayTags
{
	/*Input Config*/
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Role_Attack_Light);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Role_Attack_Heavy);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Role_Dodge);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);

	/*Player Ability*/
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dodge);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SuperComputeMatrix);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump);

	/*Player Event*/
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTargetLock);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTargetLock_Left);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTargetLock_Right);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_OnPerfectDodgeTrigger);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_TriggerSuperMatrix);

	/*Player Status*/
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLocking);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Dodging);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Cooldown_SuperMatrix);

	/*Enemy Tags*/
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_ProjectileShoot);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	
	/*Shared*/
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Invincible);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Death);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Falling);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_IsAttacking);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Attacking_Light_01);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Attacking_Light_02);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Attacking_Light_03);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Attacking_Light_04);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_SpawnWeapon);
	
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Combo_Attack_Light_01);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Combo_Attack_Light_02);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Combo_Attack_Light_03);
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Combo_Attack_Light_04);

	/*Set By Caller*/
	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	DEMO2026_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_ComboWindow);
}